name: autobuild

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  windows-build:
    name: Windows build
    runs-on: windows-2019

    env:
      buildDir: '${{ github.workspace }}/build'
      CMAKE_BUILD_PARALLEL_LEVEL: 2

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: '0'

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          vcpkgTriplet: ${{ matrix.triplet }}
          additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed

      - name: Install dependencies
        run: cmake -G'Visual Studio 16 2019' -A x64 -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_MANIFEST_MODE:BOOL=ON -DVCPKG_MANIFEST_INSTALL:BOOL=ON  -DVCPKG_TARGET_TRIPLET="x64-windows" -S . -B ${{ env.buildDir }}

      - name: Build project
        run: cmake --build ${{ env.buildDir }}
  
  linux-build:
    name: Linux build
    runs-on: ubuntu-20.04

    env:
      buildDir: '${{ github.workspace }}/build'
      CMAKE_BUILD_PARALLEL_LEVEL: 2

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: '0'

      - name: Install ninja
        run: |
          sudo apt update
          sudo apt install -y ninja-build

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          vcpkgTriplet: ${{ matrix.triplet }}
          additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed

      - name: Install dependencies
        run: cmake -G'Ninja' -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_MANIFEST_MODE:BOOL=ON -DVCPKG_MANIFEST_INSTALL:BOOL=ON  -DVCPKG_TARGET_TRIPLET="x64-linux" -S . -B ${{ env.buildDir }}

      - name: Build project
        run: cmake --build ${{ env.buildDir }}
